# Generated by Django 4.2.1 on 2023-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_sell', '0002_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(max_length=25),
        ),
    ]
