# Generated by Django 4.2.1 on 2023-09-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_sell', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
