# Generated by Django 4.2.1 on 2023-09-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_profiledetials_profile_pic'),
        ('main_sell', '0004_rename_update_at_listing_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_sell.listing')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profiledetials')),
            ],
        ),
    ]
