# Generated by Django 4.2.1 on 2023-09-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_profiledetials_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetials',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.location'),
        ),
    ]
