# Generated by Django 4.2.1 on 2023-09-10 13:05

from django.db import migrations, models
import userapp.comman_utils


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_profiledetials_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetials',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=userapp.comman_utils.get_dirctory),
        ),
    ]
